[package]
name = "rig-companion"
version = "0.1.0"
edition = "2024"
default-run = "rig-companion"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
directories = "6"
glam = "0.30"
iced = { version = "0.14", default-features = false, features = ["wgpu", "tokio", "canvas", "image-without-codecs"] }
json_comments = "0.2.2"
libloading = "0.8"
openvr_sys = "2.1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serialport = { version = "4.9", default-features = false }
tempfile = "3"
tokio = { version = "1.53.1", features = ["rt"] }
vigem-client = "0.1.4"
windows-sys = { version = "0.61", features = ["Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging", "Win32_System_Threading", "Win32_UI_Input_XboxController", "Win32_System_Diagnostics_ToolHelp", "Win32_UI_Shell", "Win32_Security"] }

[profile.release]
lto = "thin"
strip = true

[build-dependencies]
winresource = "0.1.31"
